/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Light mode tokens
        primary: '#3B82F6',
        'primary-light': '#DBEAFE',
        secondary: '#8B5CF6',
        'secondary-light': '#EDE9FE',
        accent: '#F59E0B',
        surface: '#FFFFFF',
        foreground: '#0F172A',
        'foreground-muted': '#64748B',
        'user-input': '#3B82F6',
        error: '#EF4444',
        'error-light': '#FEE2E2',
        border: '#E2E8F0',
        'border-thick': '#334155',
        note: '#64748B',
        hint: '#059669',
        background: '#F0F4FF',
        // 功能色
        'func-undo': '#94A3B8',
        'func-erase': '#EF4444',
        'func-notes': '#8B5CF6',
        'func-hint': '#F59E0B',
        // 难度色
        'diff-easy': '#22C55E',
        'diff-medium': '#F59E0B',
        'diff-hard': '#F97316',
        'diff-expert': '#EF4444',
        // 生命值
        life: '#EF4444',
        'life-lost': '#D1D5DB',
        // 数字键盘
        'numpad-bg': '#3B82F6',
        'numpad-shadow': '#2563EB',
        // 反馈条
        success: '#22C55E',
        'success-shadow': '#15803D',
        'error-shadow': '#B91C1C',
        // Dark mode tokens
        'dark-primary': '#60A5FA',
        'dark-primary-light': '#1E3A5F',
        'dark-secondary': '#A78BFA',
        'dark-secondary-light': '#2D2054',
        'dark-accent': '#FBBF24',
        'dark-background': '#0F172A',
        'dark-surface': '#1E293B',
        'dark-foreground': '#F1F5F9',
        'dark-foreground-muted': '#94A3B8',
        'dark-user-input': '#60A5FA',
        'dark-error': '#F87171',
        'dark-error-light': '#451A1A',
        'dark-border': '#334155',
        'dark-border-thick': '#CBD5E1',
        'dark-note': '#94A3B8',
        'dark-hint': '#34D399',
        'dark-func-undo': '#64748B',
        'dark-func-erase': '#F87171',
        'dark-func-notes': '#A78BFA',
        'dark-func-hint': '#FBBF24',
        'dark-diff-easy': '#4ADE80',
        'dark-diff-medium': '#FBBF24',
        'dark-diff-hard': '#FB923C',
        'dark-diff-expert': '#F87171',
        'dark-life': '#F87171',
        'dark-life-lost': '#475569',
        'dark-numpad-bg': '#60A5FA',
        'dark-numpad-shadow': '#3B82F6',
        'dark-success': '#4ADE80',
        'dark-success-shadow': '#16A34A',
        'dark-error-shadow': '#DC2626',
      },
    },
  },
  plugins: [],
}
