import type { Theme } from "./types";

export const themes: Record<string, Theme> = {
  light: {
    id: "light",
    nameKey: "theme.light",
    colors: {
      light: {
        background: "#F8FAFC",
        surface: "#FFFFFF",
        foreground: "#0F172A",
        foregroundMuted: "#64748B",
        primary: "#2563EB",
        primaryLight: "#DBEAFE",
        secondary: "#7C3AED",
        secondaryLight: "#EDE9FE",
        accent: "#F59E0B",
        userInput: "#2563EB",
        error: "#DC2626",
        errorLight: "#FEE2E2",
        border: "#E2E8F0",
        borderThick: "#334155",
        note: "#64748B",
        hint: "#059669",
      },
      dark: {
        background: "#F8FAFC",
        surface: "#FFFFFF",
        foreground: "#0F172A",
        foregroundMuted: "#64748B",
        primary: "#2563EB",
        primaryLight: "#DBEAFE",
        secondary: "#7C3AED",
        secondaryLight: "#EDE9FE",
        accent: "#F59E0B",
        userInput: "#2563EB",
        error: "#DC2626",
        errorLight: "#FEE2E2",
        border: "#E2E8F0",
        borderThick: "#334155",
        note: "#64748B",
        hint: "#059669",
      },
    },
  },

  dark: {
    id: "dark",
    nameKey: "theme.dark",
    colors: {
      light: {
        background: "#0F172A",
        surface: "#1E293B",
        foreground: "#F1F5F9",
        foregroundMuted: "#94A3B8",
        primary: "#60A5FA",
        primaryLight: "#1E3A5F",
        secondary: "#A78BFA",
        secondaryLight: "#2D2054",
        accent: "#FBBF24",
        userInput: "#60A5FA",
        error: "#F87171",
        errorLight: "#451A1A",
        border: "#334155",
        borderThick: "#CBD5E1",
        note: "#94A3B8",
        hint: "#34D399",
      },
      dark: {
        background: "#0F172A",
        surface: "#1E293B",
        foreground: "#F1F5F9",
        foregroundMuted: "#94A3B8",
        primary: "#60A5FA",
        primaryLight: "#1E3A5F",
        secondary: "#A78BFA",
        secondaryLight: "#2D2054",
        accent: "#FBBF24",
        userInput: "#60A5FA",
        error: "#F87171",
        errorLight: "#451A1A",
        border: "#334155",
        borderThick: "#CBD5E1",
        note: "#94A3B8",
        hint: "#34D399",
      },
    },
  },
};
